wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696542894.61355
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.11
      8:
      - 5
      13: darwin-x86_64
