wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696595277.288971
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.11
      8:
      - 5
      13: darwin-x86_64
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
val_percent:
  desc: null
  value: 0.1
save_checkpoint:
  desc: null
  value: true
n_channels:
  desc: null
  value: 39
analysis_period:
  desc: null
  value: summer
target:
  desc: null
  value: bias
