wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729250321.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 15
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
val_percent:
  desc: null
  value: 0.1
save_checkpoint:
  desc: null
  value: true
n_channels:
  desc: null
  value: 51
analysis_period:
  desc: null
  value: summer
target:
  desc: null
  value: bias
region:
  desc: null
  value: NorthAmerica
model:
  desc: null
  value: cqr
test_year:
  desc: null
  value: '2019'
